# 数据重塑
## 重塑层次化

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.DataFrame({'A':['A0','A1','A2'],
                 'B':['B0','B1','B2']})
df

    A   B
0  A0  B0
1  A1  B1
2  A2  B2

In [4]:
ret = df.stack()
ret

0  A    A0
   B    B0
1  A    A1
   B    B1
2  A    A2
   B    B2
dtype: object

In [5]:
type(ret)

pandas.core.series.Series

In [6]:
ret.unstack()

    A   B
0  A0  B0
1  A1  B1
2  A2  B2

In [7]:
df = pd.DataFrame(np.array([[26,20,22,26],[30,25,24,20]]),
                   index=['男生人数','女生人数'],
                   columns=[['一楼','一楼','二楼','二楼'],
                              ['A教室','B教室','A教室','B教室']])
df

      一楼      二楼
     A教室 B教室 A教室 B教室
男生人数  26  20  22  26
女生人数  30  25  24  20

In [8]:
df.stack()

C:\Users\yandifei\AppData\Local\Temp\ipykernel_39156\3977694045.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df.stack()

          一楼  二楼
男生人数 A教室  26  22
     B教室  20  26
女生人数 A教室  30  24
     B教室  25  20

In [10]:
df.stack(level=0)

C:\Users\yandifei\AppData\Local\Temp\ipykernel_39156\4116294391.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df.stack(level=0)

         A教室  B教室
男生人数 一楼   26   20
     二楼   22   26
女生人数 一楼   30   25
     二楼   24   20

In [11]:
df =  pd.DataFrame({'商品名称': ['荣耀9青春版','小米6x','OPPO A1',
                   '荣耀9青春版','小米6x','OPPO A1'],
                   '出售日期': ['2017年5月25日', '2017年5月25日',
                   '2017年5月25日','2017年6月18日',
                   '2017年6月18日', '2017年6月18日'],
                   '价格': ['999元', '1399元', '1399元',
                   '800元', '1200元', '1250元']})
df

      商品名称        出售日期     价格
0   荣耀9青春版  2017年5月25日   999元
1     小米6x  2017年5月25日  1399元
2  OPPO A1  2017年5月25日  1399元
3   荣耀9青春版  2017年6月18日   800元
4     小米6x  2017年6月18日  1200元
5  OPPO A1  2017年6月18日  1250元

In [12]:
df.pivot(index='出售日期',columns='商品名称',values='价格')

商品名称       OPPO A1   小米6x 荣耀9青春版
出售日期
2017年5月25日   1399元  1399元   999元
2017年6月18日   1250元  1200元   800元

# 数据转换
## 重名名轴索引

In [15]:
df = pd.DataFrame({'A':['A0', 'A1', 'A2', 'A3'],
                 'B':['B0', 'B1', 'B2', 'B3'],
                 'C':['C0', 'C1', 'C2', 'C3']})
df

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3

In [ ]:
# 使用rename方法对DataFrame的列名进行重命名
df.rename(columns={"A":"a","B":"b","C":"c"})

    a   b   c
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3

In [18]:
# 使用rename方法将DataFrame的列名转换为小写
# str.lower是一个字符串方法，用于将字符串转换为小写
# axis="columns"指定了对列名进行操作，而不是对行索引
df.rename(str.lower, axis="columns")

    a   b   c
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3

In [23]:
# 使用rename方法对DataFrame的索引进行重命名
# index参数用于指定要修改的索引映射关系
# {1:"a", 2:"b"}表示将索引值为1的改为"a"，索引值为2的改为"b"
df.rename(index={1:"a",2:"b"})

    A   B   C
0  A0  B0  C0
a  A1  B1  C1
b  A2  B2  C2
3  A3  B3  C3

## 数据值替换

In [25]:
df = pd.DataFrame({'姓名': ['李红','小明','马芳','国志'],
                   '性别': ['0','1','0','1'],
                   '籍贯': ['北京','甘肃','','上海']})
df

   姓名 性别  籍贯
0  李红  0  北京
1  小明  1  甘肃
2  马芳  0
3  国志  1  上海

In [40]:
df.replace("","广州", inplace=True)
df

   姓名 性别  籍贯
0  李红  0  北京
1  小明  1  甘肃
2  马芳  0  广州
3  国志  1  上海

In [41]:
df.replace(["帝都","北京"],["魔都","上海"])

   姓名 性别  籍贯
0  李红  0  上海
1  小明  1  甘肃
2  马芳  0  广州
3  国志  1  上海

In [42]:
df.replace({0:"女",1:"男"})

   姓名 性别  籍贯
0  李红  0  北京
1  小明  1  甘肃
2  马芳  0  广州
3  国志  1  上海

## 离散化连续数据

In [43]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 32]
bins = [0, 18, 25, 35, 60, 100]

In [45]:
pd.cut(ages, bins)

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (35, 60], (25, 35], (60, 100], (35, 60], (25, 35]]
Length: 11
Categories (5, interval[int64, right]): [(0, 18] < (18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [46]:
df1 = pd.DataFrame({'职业': ['工人', '学生', '司机', '教师', '导游']})
df1

   职业
0  工人
1  学生
2  司机
3  教师
4  导游

In [48]:
pd.get_dummies(df1,prefix={"col"})

   col_司机  col_学生  col_导游  col_工人  col_教师
0   False   False   False    True   False
1   False    True   False   False   False
2    True   False   False   False   False
3   False   False   False   False    True
4   False   False    True   False   False