In [1]:
import pandas as pd
import numpy as np

In [4]:
bj = pd.read_csv('北京地区信息.csv', encoding='gbk')
bj

   省级单位 地级单位  县级单位 区划类型  行政面积（K㎡）  户籍人口（万人）      男性      女性  GDP（亿元）  常住人口（万人）
0    北京   北京   西城区  市辖区        51    146.47   72.88   73.59  3602.36     125.9
1    北京   北京   东城区  市辖区        42     97.41   47.91   49.50  2061.80      87.8
2    北京   北京   丰台区  市辖区       306    115.33   58.39   56.95  1297.03     225.5
3    北京   北京   西城区  市辖区        51    146.47   72.88   73.59  3602.36     125.9
4    北京   北京   朝阳区  市辖区       455    210.91  105.43  105.48  5171.03     385.6
5    北京   北京   房山区  市辖区      1990     81.28   40.76   40.52   606.61     109.6
6    北京   北京   丰台区  市辖区       306    115.33   58.39   56.95  1297.03     225.5
7    北京   北京  石景山区  市辖区        84     38.69   19.87   18.82   482.14      63.4
8    北京   北京   海淀区  市辖区       431    240.20  120.08  120.12  5395.16     359.3
9    北京   北京   房山区  市辖区      1990     81.28   40.76   40.52   606.61     109.6
10   北京   北京   通州区  市辖区       906     74.68   37.08   37.60   674.81     142.8
11   北京   北京   顺义区  市辖区      1020     62.74   31.12   31.61  1591.60     107.5
12   北京   北京   昌平区  市辖区      1344     61.14   30.72   30.41   753.39     201.0
13   北京   北京   大兴区  市辖区      1036     68.38   34.02   34.36  1796.95     169.4
14   北京   北京  门头沟区  市辖区      1451     25.12   12.80   12.32   157.86      31.1
15   北京   北京   怀柔区  市辖区      2123     28.29   14.13   14.16   259.41      39.3
16   北京   北京   平谷区  市辖区       950     40.20   20.22   19.98   218.31      43.7
17   北京   北京   密云区  市辖区      2229     43.59   21.77   21.82   251.13      48.3
18   北京   北京   延庆区  市辖区      1994     28.42   14.32   14.11   122.66      32.7

In [ ]:
tj = pd.read_csv('北京地区信息.csv', encoding='gbk')
tj

   省级单位 地级单位  县级单位 区划类型  行政面积（K㎡）  户籍人口（万人）     男性     女性  GDP（亿元）  常住人口（万人）
0    天津   天津   和平区  市辖区        10     42.32  20.37  21.95   802.62     35.19
1    天津   天津   河东区  市辖区        39     75.79  38.06  37.73   290.98     97.61
2    天津   天津   河西区  市辖区        37     83.20  40.83  42.37   819.85     99.25
3    天津   天津   南开区  市辖区        39     87.28  43.30  43.98   652.09    114.55
4    天津   天津   河北区  市辖区        27     63.42  31.86  31.56   415.67     89.24
5    天津   天津   红桥区  市辖区        21     51.66  25.93  25.73   208.16     56.69
6    天津   天津   东丽区  市辖区       460     37.70  18.83  18.87   927.08     76.04
7    天津   天津   西青区  市辖区       545     14.85  19.85  20.38  1040.27     85.37
8    天津   天津   津南区  市辖区       401     44.83  22.35  22.48   810.16     89.41
9    天津   天津   北辰区  市辖区       478     40.39  20.09  20.30  1058.14       NaN
10   天津   天津   武清区  市辖区      1570     92.27  45.86  46.41  1151.65    119.96
11   天津   天津   宝坻区  市辖区      1523     71.10  35.72  35.39   684.07     92.98
12   天津   天津  滨海新区  市辖区      2270    128.18  66.04  62.14  6654.00    299.42
13   天津   天津   宁河区  市辖区      1414     40.00  20.21  19.79   525.37     49.57
14   天津   天津   静海区  市辖区      1476     59.79  30.35  29.44   667.83     79.29
15   天津   天津   蓟州区  市辖区      1593     86.24  43.86  42.38   392.55     91.15

In [7]:
bj.duplicated()

0     False
1     False
2     False
3      True
4     False
5     False
6      True
7     False
8     False
9      True
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
dtype: bool

In [ ]:
# 使用drop_duplicates()方法去除重复数据
new_bj = bj.drop_duplicates()
new_bj

   省级单位 地级单位  县级单位 区划类型  行政面积（K㎡）  户籍人口（万人）      男性      女性  GDP（亿元）  常住人口（万人）
0    北京   北京   西城区  市辖区        51    146.47   72.88   73.59  3602.36     125.9
1    北京   北京   东城区  市辖区        42     97.41   47.91   49.50  2061.80      87.8
2    北京   北京   丰台区  市辖区       306    115.33   58.39   56.95  1297.03     225.5
4    北京   北京   朝阳区  市辖区       455    210.91  105.43  105.48  5171.03     385.6
5    北京   北京   房山区  市辖区      1990     81.28   40.76   40.52   606.61     109.6
7    北京   北京  石景山区  市辖区        84     38.69   19.87   18.82   482.14      63.4
8    北京   北京   海淀区  市辖区       431    240.20  120.08  120.12  5395.16     359.3
10   北京   北京   通州区  市辖区       906     74.68   37.08   37.60   674.81     142.8
11   北京   北京   顺义区  市辖区      1020     62.74   31.12   31.61  1591.60     107.5
12   北京   北京   昌平区  市辖区      1344     61.14   30.72   30.41   753.39     201.0
13   北京   北京   大兴区  市辖区      1036     68.38   34.02   34.36  1796.95     169.4
14   北京   北京  门头沟区  市辖区      1451     25.12   12.80   12.32   157.86      31.1
15   北京   北京   怀柔区  市辖区      2123     28.29   14.13   14.16   259.41      39.3
16   北京   北京   平谷区  市辖区       950     40.20   20.22   19.98   218.31      43.7
17   北京   北京   密云区  市辖区      2229     43.59   21.77   21.82   251.13      48.3
18   北京   北京   延庆区  市辖区      1994     28.42   14.32   14.11   122.66      32.7

In [17]:
tj.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
dtype: bool

In [13]:
new_bj.isnull()

,省级单位,地级单位,县级单位,区划类型,行政面积（K㎡）,户籍人口（万人）,男性,女性,GDP（亿元）,常住人口（万人）
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False

In [14]:
tj.isnull()

,省级单位,地级单位,县级单位,区划类型,行政面积（K㎡）,户籍人口（万人）,男性,女性,GDP（亿元）,常住人口（万人）
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,True
10,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False

In [ ]:
population = round(tj["常住人口（万人）"].mean(),2)
population

np.float64(98.38)

In [27]:
values = {"常住人口（万人）": population}

In [29]:
new_tj = tj.fillna(value=values)
new_tj

   省级单位 地级单位  县级单位 区划类型  行政面积（K㎡）  户籍人口（万人）     男性     女性  GDP（亿元）  常住人口（万人）
0    天津   天津   和平区  市辖区        10     42.32  20.37  21.95   802.62     35.19
1    天津   天津   河东区  市辖区        39     75.79  38.06  37.73   290.98     97.61
2    天津   天津   河西区  市辖区        37     83.20  40.83  42.37   819.85     99.25
3    天津   天津   南开区  市辖区        39     87.28  43.30  43.98   652.09    114.55
4    天津   天津   河北区  市辖区        27     63.42  31.86  31.56   415.67     89.24
5    天津   天津   红桥区  市辖区        21     51.66  25.93  25.73   208.16     56.69
6    天津   天津   东丽区  市辖区       460     37.70  18.83  18.87   927.08     76.04
7    天津   天津   西青区  市辖区       545     14.85  19.85  20.38  1040.27     85.37
8    天津   天津   津南区  市辖区       401     44.83  22.35  22.48   810.16     89.41
9    天津   天津   北辰区  市辖区       478     40.39  20.09  20.30  1058.14     98.38
10   天津   天津   武清区  市辖区      1570     92.27  45.86  46.41  1151.65    119.96
11   天津   天津   宝坻区  市辖区      1523     71.10  35.72  35.39   684.07     92.98
12   天津   天津  滨海新区  市辖区      2270    128.18  66.04  62.14  6654.00    299.42
13   天津   天津   宁河区  市辖区      1414     40.00  20.21  19.79   525.37     49.57
14   天津   天津   静海区  市辖区      1476     59.79  30.35  29.44   667.83     79.29
15   天津   天津   蓟州区  市辖区      1593     86.24  43.86  42.38   392.55     91.15