# 目标
## 分组与聚合
拆分、应用、聚合
## groupby方法将数据分组
groupby()方法将数据按照某些规则标准划分
不会对实际对象造成影响
标准：列名、函数、索引、字典、序列、或索引级别

In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.DataFrame({"Key":['C','B','C','A','B','B','A','C','A'],
                   "Data":[2,4,6,8,10,1,14,16,18]})
df

  Key  Data
0   C     2
1   B     4
2   C     6
3   A     8
4   B    10
5   B     1
6   A    14
7   C    16
8   A    18

In [7]:
group_obj = df.groupby(by="Key")

In [8]:
for i in group_obj:
    print(i)

('A',   Key  Data
3   A     8
6   A    14
8   A    18)
('B',   Key  Data
1   B     4
4   B    10
5   B     1)
('C',   Key  Data
0   C     2
2   C     6
7   C    16)

In [9]:
df = pd.DataFrame({'key1': ['A', 'A', 'B', 'B','A'],
                    'key2': ['one','two','one','two','one'],
                    "datal": [2, 3, 4, 6, 8],
                    "data2": [3, 5, 2, 3,7]})
df

  key1 key2  datal  data2
0    A  one      2      3
1    A  two      3      5
2    B  one      4      2
3    B  two      6      3
4    A  one      8      7

In [14]:
# 导入pandas库并创建一个Series对象
# Series是pandas中的一维标记数组，能够容纳任何数据类型
se = pd.Series(['a','b','a','c','d'])  # 使用列表创建一个包含4个元素的Series，索引默认为0-3的整数

In [15]:
# 使用pandas的groupby方法对DataFrame进行分组
# group_obj: 分组后的对象，是一个GroupBy对象
# df: 输入的DataFrame数据结构
# by: 分组的依据，这里用变量se表示分组列名
group_obj = df.groupby(by=se)

In [16]:
# 遍历group_obj对象中的每个元素
for i in group_obj:
    # 打印当前遍历到的元素i
    print(i)

('a',   key1 key2  datal  data2
0    A  one      2      3
2    B  one      4      2)
('b',   key1 key2  datal  data2
1    A  two      3      5)
('c',   key1 key2  datal  data2
3    B  two      6      3)
('d',   key1 key2  datal  data2
4    A  one      8      7)

In [57]:
df = pd.DataFrame({'a': [1, 2, 3, 4, 5],
                   'b': [6, 7, 8, 9, 10],
                   'c': [5, 4, 3, 2, 1],
                   'd': [5, 4, 3, 2, 1],
                   'e': [10, 9, 8, 7, 6]
                })

In [ ]:
mapping = {'a': "第一组",
           'b': "第二组",
           'c': "第一组",
           'd': "第三组",
           'e': "第二组"}

分组对象中的组数: 3

In [58]:
group_obj = df.groupby(by=mapping, axis=1)

C:\Users\yandifei\AppData\Local\Temp\ipykernel_29868\2335326207.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  group_obj = df.groupby(by=mapping, axis=1)

In [59]:
for name, group in group_obj:
    print(f"\n组名: {name}")
    print(group)

组名: 第一组
   a  c
0  1  5
1  2  4
2  3  3
3  4  2
4  5  1

组名: 第三组
   d
0  5
1  4
2  3
3  2
4  1

组名: 第二组
    b   e
0   6  10
1   7   9
2   8   8
3   9   7
4  10   6

In [ ]:
# 按照函数分组
df = pd.DataFrame({'a': [1, 2, 3, 4, 5], #  创建列'a'，包含5个元素
                   'b': [6, 7, 8, 9, 10], #  创建列'b'，包含5个元素
                   'c': [5, 4, 3, 2, 1]}, #  创建列'c'，包含5个元素
                    index=['Sun', 'Jack', 'Alice', 'Helen', 'Job']) #  设置行索引
df #  显示创建的DataFrame

       a   b  c
Sun    1   6  5
Jack   2   7  4
Alice  3   8  3
Helen  4   9  2
Job    5  10  1

In [ ]:
# 定义一个函数，输入参数为字符串s，返回字符串s的长度
group_obj = df.groupby(len)

In [ ]:
# 遍历group_obj对象中的每个元素
for i in group_obj:
    print(i)

(3,      a   b  c
Sun  1   6  5
Job  5  10  1)
(4,       a  b  c
Jack  2  7  4)
(5,        a  b  c
Alice  3  8  3
Helen  4  9  2)

## 汇总与统计

In [42]:
df =  pd.DataFrame(np.random.randn(3, 3), columns=['a', 'b', 'c'], index=['app', 'win', 'mac'])
df

            a         b         c
app -0.522811 -1.478523  0.432024
win -0.042189 -1.862908 -0.105939
mac  0.340447  0.471768 -0.147718

In [43]:
df.sum()

a   -0.224552
b   -2.869664
c    0.178368
dtype: float64

In [44]:
df.sum(axis=1)

app   -1.569310
win   -2.011035
mac    0.664497
dtype: float64

In [ ]:
# 使用describe()方法对DataFrame进行描述性统计分析
# 该方法会计算每列数据的计数、均值、标准差、最小值、四分位数和最大值等统计信息
df.describe()

              a         b         c
count  3.000000  3.000000  3.000000
mean  -0.074851 -0.956555  0.059456
std    0.432555  1.251805  0.323329
min   -0.522811 -1.862908 -0.147718
25%   -0.282500 -1.670716 -0.126828
50%   -0.042189 -1.478523 -0.105939
75%    0.149129 -0.503378  0.163043
max    0.340447  0.471768  0.432024

In [ ]:
# 显示DataFrame的前两行数据
df.head(2)

            a         b         c
app -0.522811 -1.478523  0.432024
win -0.042189 -1.862908 -0.105939

In [ ]:
# 使用tail方法获取DataFrame对象的最后两行数据
# tail()是pandas中DataFrame对象的一个方法，用于查看末尾数据
# 参数2表示获取最后2行数据
df.tail(2)

            a         b         c
win -0.042189 -1.862908 -0.105939
mac  0.340447  0.471768 -0.147718

## 聚合统计
### 使用内置方法统计聚合数据

In [52]:
df = pd.DataFrame({'key1': ['A', 'A', 'B', 'B','A'],
                    'key2': ['one','two','one','two','one'],
                    "datal": [2, 3, 4, 6, 8],
                    "data2": [3, 5, 2, 3,7]})
df

  key1 key2  datal  data2
0    A  one      2      3
1    A  two      3      5
2    B  one      4      2
3    B  two      6      3
4    A  one      8      7

In [ ]:
# 使用pandas的groupby方法按照"key1"列进行分组，并计算每组的平均值
# numeric_only=True参数表示只计算数值列的均值，忽略非数值列
df.groupby("key1").mean(numeric_only=True)

         datal  data2
key1
A     4.333333    5.0
B     5.000000    2.5

## 面向列的聚合方法（agg）

In [67]:
data_frame = pd.DataFrame (np.arange(36).reshape ((6, 6)),
                           columns=list('abcdef'))
data_frame['key'] = pd.Series(list('aaabbb'), name='key')
data_frame

    a   b   c   d   e   f key
0   0   1   2   3   4   5   a
1   6   7   8   9  10  11   a
2  12  13  14  15  16  17   a
3  18  19  20  21  22  23   b
4  24  25  26  27  28  29   b
5  30  31  32  33  34  35   b

In [ ]:
# 对DataFrame按照"key"列进行分组
data_group = data_frame.groupby("key")
# 获取分组中键为'a'的所有数据索引
data_group.groups['a']

Index([0, 1, 2], dtype='int64')

In [72]:
#  使用iloc方法根据分组结果获取特定组的数据 data_frame 是一个数据框对象 data_group 是一个分组对象，通过groups属性可以获取每个组的数据索引 'a' 是分组的键名，表示要获取的特定组 最终返回的是分组键为'a'的所有数据行
data_frame.iloc[data_group.groups['a']]

    a   b   c   d   e   f key
0   0   1   2   3   4   5   a
1   6   7   8   9  10  11   a
2  12  13  14  15  16  17   a

In [73]:
# 使用iloc方法根据分组结果获取特定组的数据 data_frame 是一个数据框对象 data_group 是一个分组对象，通过groups属性可以获取每个组的数据索引 'a' 是分组的键名，表示要获取的特定组 最终返回的是分组键为'a'的所有数据行
data_frame.iloc[data_group.groups['a']]

    a   b   c   d   e   f key
0   0   1   2   3   4   5   a
1   6   7   8   9  10  11   a
2  12  13  14  15  16  17   a

In [75]:
# 个警告 FutureWarning 的含义是：你当前传递给 agg 的参数是一个函数对象（sum），但在未来的 Pandas 版本中，这种行为将会改变。为了避免未来的代码报错，建议直接传递字符串 "sum"
data_group.agg("sum")

      a   b   c   d   e   f
key
a    18  21  24  27  30  33
b    72  75  78  81  84  87

In [76]:
# 求极差值
def range_dat_group(arr):
    return arr.max() - arr.min()

In [79]:
data_group.agg(range_dat_group)

      a   b   c   d   e   f
key
a    12  12  12  12  12  12
b    12  12  12  12  12  12

In [86]:
# 对一组数据用两种函数聚合
data_group.agg([range_dat_group, "sum"])

                  a                   b                   c      \
    range_dat_group sum range_dat_group sum range_dat_group sum
key
a                12  18              12  21              12  24
b                12  72              12  75              12  78

                  d                   e                   f
    range_dat_group sum range_dat_group sum range_dat_group sum
key
a                12  27              12  30              12  33
b                12  81              12  84              12  87

In [87]:
data_group.agg([("极差值", range_dat_group), ("总和", "sum")])

      a       b       c       d       e       f
    极差值  总和 极差值  总和 极差值  总和 极差值  总和 极差值  总和 极差值  总和
key
a    12  18  12  21  12  24  12  27  12  30  12  33
b    12  72  12  75  12  78  12  81  12  84  12  87

In [90]:
# 每列使用不同的函数集合
data_group.agg({"a": range_dat_group, "b": "sum", "c": range_dat_group, "d": "sum"})

      a   b   c   d
key
a    12  21  12  27
b    12  75  12  81

# 其他分组级运算
## 数据转型(transfer)

In [91]:
df = pd.DataFrame({'a':[0,1,6,10,3],
                   'b':[1,2,7,11,4],
                   'c':[2,3,8,12,4],
                   'd':[3,4,9,13,5],
                   'e':[4,5,10,14,3],
                   'key':['A','A','B','B','B'],
})
df

    a   b   c   d   e key
0   0   1   2   3   4   A
1   1   2   3   4   5   A
2   6   7   8   9  10   B
3  10  11  12  13  14   B
4   3   4   4   5   3   B

In [92]:
obj = df.groupby("key")

In [94]:
for i in obj:
    print(i)

('A',    a  b  c  d  e key
0  0  1  2  3  4   A
1  1  2  3  4  5   A)
('B',     a   b   c   d   e key
2   6   7   8   9  10   B
3  10  11  12  13  14   B
4   3   4   4   5   3   B)

In [ ]:
# 使用pandas的groupby方法按"key"列对数据框df进行分组，然后应用transform方法计算每组的平均值
# transform方法会将计算结果广播回原始数据框的形状，即每个原始行都会显示其对应组的平均值
obj = df.groupby("key").transform("mean")
obj

          a         b    c    d    e
0  0.500000  1.500000  2.5  3.5  4.5
1  0.500000  1.500000  2.5  3.5  4.5
2  6.333333  7.333333  8.0  9.0  9.0
3  6.333333  7.333333  8.0  9.0  9.0
4  6.333333  7.333333  8.0  9.0  9.0

In [104]:
df=pd.DataFrame({'A':[2,3,3,4,2],
                 'B':[4,2,3,6,6],
                 'C':[9,7,0,7,8],
                 'D':[3, 4,8,6,10]})
df

   A  B  C   D
0  2  4  9   3
1  3  2  7   4
2  3  3  0   8
3  4  6  7   6
4  2  6  8  10

In [105]:
key = ['one', 'one', 'two', 'two', 'two']

In [108]:
df.groupby(by=key).transform("mean")

     A    B    C    D
0  2.5  3.0  8.0  3.5
1  2.5  3.0  8.0  3.5
2  3.0  5.0  5.0  8.0
3  3.0  5.0  5.0  8.0
4  3.0  5.0  5.0  8.0

## 数据应用（apply）

In [110]:
data_frame = pd.DataFrame({'datal': [80,23,25,63,94,92,99,92,82,99],
                            'data2': [41,87,58,68,72,89,60,42,53,65],
                            'data3': [30,78,23,66,16,59,20,23,24,40]})
data_frame

   datal  data2  data3
0     80     41     30
1     23     87     78
2     25     58     23
3     63     68     66
4     94     72     16
5     92     89     59
6     99     60     20
7     92     42     23
8     82     53     24
9     99     65     40

In [ ]:
# 使用apply方法对DataFrame的每一列应用一个lambda函数
# 该lambda函数计算每列的最大值与最小值之差，即每列的极差
data_frame.apply(lambda x: x.max() - x.min())

datal    76
data2    48
data3    62
dtype: int64