# 实训
## 需求
## 1. 查询篮球分组信息
## 2. 查看男运动员分组
## 3. 查看男篮分组年龄、身高、体重三列数的极差值
## 4. 添加体质指数BIM值=身高/体重^2

In [1]:
import pandas as pd
import numpy as np

In [36]:
csv = pd.read_csv("运动员信息表.csv", encoding="ANSI")
print(csv)

       姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)      项目     省份
0     陈楠   女   1983年     35     197      90      篮球    山东省
1    白发全   男   1986年     32     175      64    铁人三项    云南省
2    陈晓佳   女   1988年     30     180      70      篮球    江苏省
3     陈倩   女   1987年     31     163      54  女子现代五项  江苏省
4    曹忠荣   男   1981年     37     180      73  男子现代五项    上海市
..    ... ..     ...    ...     ...     ...     ...    ...
174  赵芸蕾   女   1986年     32     173      62     羽毛球    湖北省
175   周琦   男   1996年     22     217      95      篮球   河南省
176  翟晓川   男   1993年     25     204     100      篮球   河北省
177  赵继伟   男   1995年     23     185      77      篮球    辽宁省
178  邹雨宸   男   1996年     22     208     108      篮球    辽宁省

[179 rows x 8 columns]

In [9]:
# 查询篮球分组信息
csv.groupby(by="项目").get_group("篮球")

        姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)  项目        省份
0      陈楠   女   1983年     35     197      90  篮球       山东省
2     陈晓佳   女   1988年     30     180      70  篮球       江苏省
16   丁彦雨航   男   1993年     25     200      91  篮球  新疆维吾尔自治区
23     高颂   女   1992年     26     191      85  篮球    黑龙江省
28    郭艾伦   男   1993年     25     192      85  篮球       辽宁省
35    黄红枇   女   1989年     29     195      80  篮球   广西壮族自治区
42    黄思静   女   1996年     22     192      80  篮球       广东省
48    李慕豪   男   1992年     26     225     111  篮球      贵州贵阳
54    李珊珊   女   1987年     31     177      70  篮球     江苏省
73     露雯   女   1990年     28     191      78  篮球    内蒙古自治区
101   孙梦然   女   1992年     26     197      77  篮球       天津市
102   孙梦昕   女   1993年     25     190      77  篮球     山东省
106    睢冉   男   1992年     26     192      95  篮球       山西省
116    吴迪   女   1990年     28     186      72  篮球       天津市
124   王哲林   男   1994年     24     214     110  篮球      福建省
155   易建联   男   1987年     31     213     113  篮球       广东省
161    周鹏   男   1989年     29     206      90  篮球       辽宁省
175    周琦   男   1996年     22     217      95  篮球      河南省
176   翟晓川   男   1993年     25     204     100  篮球      河北省
177   赵继伟   男   1995年     23     185      77  篮球       辽宁省
178   邹雨宸   男   1996年     22     208     108  篮球       辽宁省

In [14]:
## 2. 查看男运动员分组
csv.groupby("性别").get_group("男")

       姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)        项目     省份
1    白发全   男   1986年     32     175      64      铁人三项    云南省
4    曹忠荣   男   1981年     37     180      73    男子现代五项    上海市
5     曹缘   男   1995年     23     160      42        跳水    北京市
6     曹硕   男   1991年     27     180      76    男子三级跳远  河北省
8     陈定   男   1992年     26     177      61  男子20公里竞走  云南省
..    ... ..     ...    ...     ...     ...       ...    ...
173  张培萌   男   1987年     31     186      86        田径    北京市
175   周琦   男   1996年     22     217      95        篮球   河南省
176  翟晓川   男   1993年     25     204     100        篮球   河北省
177  赵继伟   男   1995年     23     185      77        篮球    辽宁省
178  邹雨宸   男   1996年     22     208     108        篮球    辽宁省

[76 rows x 8 columns]

In [33]:
## 3. 查看男篮分组年龄、身高、体重三列数的极差值
# 先拿到男篮分组
data = csv.groupby("性别").get_group("男").groupby("项目").get_group("篮球")
# 使用apply方法对DataFrame的每一列应用一个lambda函数
mapping = {"年龄（岁）": lambda x: x.max() - x.min(),
           "身高(cm)": lambda x: x.max() - x.min(),
           "体重(kg)": lambda x: x.max() - x.min()
           }
# 该lambda函数计算每列的最大值与最小值之差，即每列的极差
data.agg(mapping)


# obj = csv[csv["性别"] == "男"][csv["项目"] == "篮球"]
# obj

年龄（岁）      9
身高(cm)    40
体重(kg)    36
dtype: int64

In [39]:
## 4. 添加体质指数BIM值=身高/体重^2
# csv["BIM"] = csv["身高(cm)"] / (csv["体重(kg)"] ** 2)
# csv
def bmi(height, weight):
    return (height/100) / (weight * weight)
# 该lambda函数拿到身高和体重求BIM值
csv["BIM"] = csv.apply(lambda x: bmi(x["身高(cm)"], x["体重(kg)"]), axis=1)
csv

       姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)      项目     省份       BIM
0     陈楠   女   1983年     35     197      90      篮球    山东省  0.000243
1    白发全   男   1986年     32     175      64    铁人三项    云南省  0.000427
2    陈晓佳   女   1988年     30     180      70      篮球    江苏省  0.000367
3     陈倩   女   1987年     31     163      54  女子现代五项  江苏省    0.000559
4    曹忠荣   男   1981年     37     180      73  男子现代五项    上海市  0.000338
..    ... ..     ...    ...     ...     ...     ...    ...       ...
174  赵芸蕾   女   1986年     32     173      62     羽毛球    湖北省  0.000450
175   周琦   男   1996年     22     217      95      篮球   河南省   0.000240
176  翟晓川   男   1993年     25     204     100      篮球   河北省   0.000204
177  赵继伟   男   1995年     23     185      77      篮球    辽宁省  0.000312
178  邹雨宸   男   1996年     22     208     108      篮球    辽宁省  0.000178

[179 rows x 9 columns]

In [ ]:
def BMI(df):
    weight = df["体重(kg)"]
    height = df["身高(cm)"]
    return height / (weight ** 2)

_IncompleteInputError: incomplete input (1682294130.py, line 1)