# 数据分组与聚合
## 数据分组

In [1]:
import pandas as pd
import numpy as np

In [2]:
#通过列名
df = pd.DataFrame({"Key":['C','B','C','A','B','B','A','C','A'],
                   "Data":[2,4,6,8,10,1,14,16,18]})
df

  Key  Data
0   C     2
1   B     4
2   C     6
3   A     8
4   B    10
5   B     1
6   A    14
7   C    16
8   A    18

In [4]:
group_obj = df.groupby(by='Key')

In [5]:
for i in group_obj:
    print(i)

('A',   Key  Data
3   A     8
6   A    14
8   A    18)
('B',   Key  Data
1   B     4
4   B    10
5   B     1)
('C',   Key  Data
0   C     2
2   C     6
7   C    16)

In [6]:
#通过Serios对象分组
df = pd.DataFrame({'keyl': ['A', 'A', 'B', 'B', 'A'],
                   'key2': ['one','two','one', 'two', 'one'],
                    'datal': [2, 3, 4, 6,8],
                    'data2': [3, 5, 6, 3, 7]})
df

  keyl key2  datal  data2
0    A  one      2      3
1    A  two      3      5
2    B  one      4      6
3    B  two      6      3
4    A  one      8      7

In [7]:
se = pd.Series(['a','b','a','c','b'])

In [8]:
group_obj = df.groupby(by=se)

In [9]:
for i in group_obj:
    print(i)

('a',   keyl key2  datal  data2
0    A  one      2      3
2    B  one      4      6)
('b',   keyl key2  datal  data2
1    A  two      3      5
4    A  one      8      7)
('c',   keyl key2  datal  data2
3    B  two      6      3)

In [42]:
#通过字典
df = pd.DataFrame({'a': [1, 2, 3, 4, 5],
                   'b': [6, 7, 8, 9, 10],
                   'c': [11, 12, 13, 14, 15],
                   'd':[5,4,3,2,1],
                    'e':[10,9,8,7,6]})
df

   a   b   c  d   e
0  1   6  11  5  10
1  2   7  12  4   9
2  3   8  13  3   8
3  4   9  14  2   7
4  5  10  15  1   6

In [43]:
mapping={'a':'第一组','b':'第二组','c':'第一组',
        'd':'第三组','e':'第二组'}
mapping

{'a': '第一组', 'b': '第二组', 'c': '第一组', 'd': '第三组', 'e': '第二组'}

In [47]:
group_obj = df.groupby(by=mapping,axis=1)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_6100\629474505.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  group_obj = df.groupby(by=mapping,axis=1)

In [48]:
for i in group_obj:
    print(i)

('第一组',    a   c
0  1  11
1  2  12
2  3  13
3  4  14
4  5  15)
('第三组',    d
0  5
1  4
2  3
3  2
4  1)
('第二组',     b   e
0   6  10
1   7   9
2   8   8
3   9   7
4  10   6)

In [21]:
#按照函数分组
df = pd.DataFrame({'a': [1, 2, 3, 4, 5],
                   'b': [6, 7, 8, 9, 10],
                   'c': [5, 4, 3, 2, 1]},
                    index=['Sun', 'Jack', 'Alice', 'Helen', 'Job'])
df

       a   b  c
Sun    1   6  5
Jack   2   7  4
Alice  3   8  3
Helen  4   9  2
Job    5  10  1

In [22]:
group_obj = df.groupby(len)

In [23]:
for i in group_obj:
    print(i)

(3,      a   b  c
Sun  1   6  5
Job  5  10  1)
(4,       a  b  c
Jack  2  7  4)
(5,        a  b  c
Alice  3  8  3
Helen  4  9  2)

## 汇总与统计

In [24]:
df = pd.DataFrame(np.random.randn(3,3),columns=['a','b','c'],index=['app','win','mac'])
df

            a         b         c
app -0.553314 -0.240069 -0.060741
win  0.853698  1.150961 -0.103392
mac -1.401364  0.886353  0.901958

In [25]:
df.sum()

a   -1.100980
b    1.797246
c    0.737826
dtype: float64

In [26]:
df.sum(axis=1)

app   -0.854124
win    1.901268
mac    0.386947
dtype: float64

In [27]:
df.describe()

              a         b         c
count  3.000000  3.000000  3.000000
mean  -0.366993  0.599082  0.245942
std    1.139019  0.738671  0.568527
min   -1.401364 -0.240069 -0.103392
25%   -0.977339  0.323142 -0.082066
50%   -0.553314  0.886353 -0.060741
75%    0.150192  1.018657  0.420609
max    0.853698  1.150961  0.901958

In [31]:
df.head(2)

            a         b         c
app -0.553314 -0.240069 -0.060741
win  0.853698  1.150961 -0.103392

In [32]:
df.tail(2)

            a         b         c
win  0.853698  1.150961 -0.103392
mac -1.401364  0.886353  0.901958

# 聚合统计
## 使用内置方法统计聚合数据

In [50]:
df = pd.DataFrame({'key1': ['A', 'A', 'B', 'B','A'],
                    'key2': ['one','two','one','two','one'],
                    "datal": [2, 3, 4, 6, 8],
                    "data2": [3, 5, 2, 3,7]})
df

  key1 key2  datal  data2
0    A  one      2      3
1    A  two      3      5
2    B  one      4      2
3    B  two      6      3
4    A  one      8      7

In [51]:
df.groupby(by='key1').mean

## 面向列的聚合方法（agg）

In [53]:
data_frame = pd.DataFrame (np.arange(36).reshape ((6, 6)),
                           columns=list('abcdef'))
data_frame['key'] = pd.Series(list('aaabbb'), name='key')
data_frame

    a   b   c   d   e   f key
0   0   1   2   3   4   5   a
1   6   7   8   9  10  11   a
2  12  13  14  15  16  17   a
3  18  19  20  21  22  23   b
4  24  25  26  27  28  29   b
5  30  31  32  33  34  35   b

In [55]:
data_group = data_frame.groupby(by='key')#获取分组对象
data_group.groups['a'] #获取行名称

Index([0, 1, 2], dtype='int64')

In [56]:
data_frame.iloc[data_group.groups['a']] #获取行名称相对应的数据

    a   b   c   d   e   f key
0   0   1   2   3   4   5   a
1   6   7   8   9  10  11   a
2  12  13  14  15  16  17   a

In [57]:
data_frame.iloc[data_group.groups['b']]

    a   b   c   d   e   f key
3  18  19  20  21  22  23   b
4  24  25  26  27  28  29   b
5  30  31  32  33  34  35   b

In [64]:
data_group.agg(sum)#求和

C:\Users\Administrator\AppData\Local\Temp\ipykernel_6100\2160021397.py:1: FutureWarning: The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  data_group.agg(sum)#求和

      a   b   c   d   e   f
key
a    18  21  24  27  30  33
b    72  75  78  81  84  87

In [59]:
# 求极差值
def rang_data_group(arr):
    return arr.max() -arr.min()

In [62]:
data_group.agg(rang_data_group)

      a   b   c   d   e   f
key
a    12  12  12  12  12  12
b    12  12  12  12  12  12

In [70]:
# 对一组数据用两种函数聚合
data_group.agg([rang_data_group,'sum'])

                  a                   b                   c      \
    rang_data_group sum rang_data_group sum rang_data_group sum
key
a                12  18              12  21              12  24
b                12  72              12  75              12  78

                  d                   e                   f
    rang_data_group sum rang_data_group sum rang_data_group sum
key
a                12  27              12  30              12  33
b                12  81              12  84              12  87

In [69]:
data_group.agg([('极差值',rang_data_group),('求和','sum')])

      a       b       c       d       e       f
    极差值  求和 极差值  求和 极差值  求和 极差值  求和 极差值  求和 极差值  求和
key
a    12  18  12  21  12  24  12  27  12  30  12  33
b    12  72  12  75  12  78  12  81  12  84  12  87

In [72]:
# 每列使用不同函数聚合
data_group.agg({'a':'sum','b':'mean','c':rang_data_group,'d':'std'})

      a     b   c    d
key
a    18   7.0  12  6.0
b    72  25.0  12  6.0

## 其他分组级运算
### 数据转型（transform）

In [73]:
df = pd.DataFrame({'a':[0,1,6,10,3],
                   'b':[1,2,7,11,4],
                   'c':[2,3,8,12,4],
                   'd':[3,4,9,13,5],
                   'e':[4,5,10,14,3],
                   'key':['A','A','B','B','B'],
})
df

    a   b   c   d   e key
0   0   1   2   3   4   A
1   1   2   3   4   5   A
2   6   7   8   9  10   B
3  10  11  12  13  14   B
4   3   4   4   5   3   B

In [77]:
df.groupby(by='key').transform('mean')

          a         b    c    d    e
0  0.500000  1.500000  2.5  3.5  4.5
1  0.500000  1.500000  2.5  3.5  4.5
2  6.333333  7.333333  8.0  9.0  9.0
3  6.333333  7.333333  8.0  9.0  9.0
4  6.333333  7.333333  8.0  9.0  9.0

In [78]:
df=pd.DataFrame({'A':[2,3,3,4,2],
                 'B':[4,2,3,6,6],
                 'C':[9,7,0,7,8],
                 'D':[3, 4,8,6,10]})
df

   A  B  C   D
0  2  4  9   3
1  3  2  7   4
2  3  3  0   8
3  4  6  7   6
4  2  6  8  10

In [79]:
key=['one','one','two','two','two']

In [81]:
df.groupby(by=key).transform('mean')

     A    B    C    D
0  2.5  3.0  8.0  3.5
1  2.5  3.0  8.0  3.5
2  3.0  5.0  5.0  8.0
3  3.0  5.0  5.0  8.0
4  3.0  5.0  5.0  8.0

## 数据应用（apply）

In [82]:
data_frame = pd.DataFrame({'datal': [80,23,25,63,94,92,99,92,82,99],
                            'data2': [41,87,58,68,72,89,60,42,53,65],
                            'data3': [30,78,23,66,16,59,20,23,24,40]})
data_frame

   datal  data2  data3
0     80     41     30
1     23     87     78
2     25     58     23
3     63     68     66
4     94     72     16
5     92     89     59
6     99     60     20
7     92     42     23
8     82     53     24
9     99     65     40

In [83]:
data_frame.apply(lambda x:x.max() - x.min())

datal    76
data2    48
data3    62
dtype: int64