使用以下数据创建一个 DataFrame：
姓名：张三、李四、王五、赵六、钱七
年龄：20、21、19、22、20
成绩：85、92、78、90、88
班级：1 班、2 班、1 班、2 班、1 班
完成以下操作：
（1）查看 DataFrame 的前 3 行
（2）查看数据的行列数（形状）
（3）查看每列的数据类型
（4）查看数据的基本统计信息（均值、最值等）
（5）将 姓名 列设置为行索引
（6）使用标签索引获取： 
李四的所有信息
王五和赵六的年龄和成绩
（7）使用位置索引获取：
第 2 行到第 4 行的所有数据
第 1 列和第 3 列
（8）查询年龄大于20的所有学生
（9）查询 成绩 ≥ 90 且 班级为 2 班 的学生
（10）查询姓名是 张三或王五 的记录
（11）查询 成绩在 80～90 之间 的学生
（12）将 赵六的年龄修改为 23
（13）删除 班级 这一列
（14）删除 成绩低于 80 的行

In [1]:
import pandas as pd

In [28]:
# 姓名：张三、李四、王五、赵六、钱七
# 年龄：20、21、19、22、20
# 成绩：85、92、78、90、88
# 班级：1 班、2 班、1 班、2 班、1 班
data = pd.DataFrame({
    "姓名": ["张三", "李四", "王五", "赵六", "钱七"],
    "年龄": [20, 21, 19, 22, 20],
    "成绩": [85, 92, 78, 90, 88],
    "班级": ["1 班", "2 班", "1 班", "2 班", "1 班"]
})
data

   姓名  年龄  成绩   班级
0  张三  20  85  1 班
1  李四  21  92  2 班
2  王五  19  78  1 班
3  赵六  22  90  2 班
4  钱七  20  88  1 班

In [7]:
# （1）查看 DataFrame 的前 3 行
data.head(3)

   姓名  年龄  成绩   班级
0  张三  20  85  1 班
1  李四  21  92  2 班
2  王五  19  78  1 班

In [8]:
# （2）查看数据的行列数（形状）
data.shape

(5, 4)

In [9]:
# （3）查看每列的数据类型
data.dtypes

姓名    object
年龄     int64
成绩     int64
班级    object
dtype: object

In [24]:
# （4）查看数据的基本统计信息（均值、最值等）
data.describe()

              年龄         成绩
count   5.000000   5.000000
mean   20.400000  86.600000
std     1.140175   5.458938
min    19.000000  78.000000
25%    20.000000  85.000000
50%    20.000000  88.000000
75%    21.000000  90.000000
max    22.000000  92.000000

In [26]:
# （5）将 姓名 列设置为行索引
data.set_index('姓名', inplace=True)
data

    年龄  成绩   班级
姓名
张三  20  85  1 班
李四  21  92  2 班
王五  19  78  1 班
赵六  22  90  2 班
钱七  20  88  1 班

In [27]:
# （6）使用标签索引获取：
data.loc['李四']    # 字典的写法

年龄     21
成绩     92
班级    2 班
Name: 李四, dtype: object

In [15]:
# 王五和赵六的年龄和成绩
data.loc[['王五', '赵六'], ['年龄', '成绩']]

    年龄  成绩
姓名
王五  19  78
赵六  22  90

In [16]:
# （7）使用位置索引获取：
# 第 2 行到第 4 行的所有数据
data.iloc[1:4]

    年龄  成绩   班级
姓名
李四  21  92  2 班
王五  19  78  1 班
赵六  22  90  2 班

In [18]:
# 第 1 列和第 3 列
# 姓名和成绩（直接字典方式读取）
data.iloc[:, [0, 2]]

    年龄   班级
姓名
张三  20  1 班
李四  21  2 班
王五  19  1 班
赵六  22  2 班
钱七  20  1 班

In [19]:
# （8）查询年龄大于20的所有学生
data[data.年龄 > 20]

    年龄  成绩   班级
姓名
李四  21  92  2 班
赵六  22  90  2 班

In [21]:
# （9）查询 成绩 ≥ 90 且 班级为 2 班 的学生

# 错误示范
# data[data.成绩 >= 90 & data.班级 == "2"]
# 运算符优先级问题&（按位与）的优先级高于比较运算符（>= 和 ==），导致表达式被错误解析为：data[data.成绩 >= (90 & data.班级) == "2"]
data[(data.成绩 >= 90) & (data.班级 == "2 班")]
# 注意：and作为关键字无法在这里使用，必须要&符，否则会报错，还有被比较数一定号对上(2空格班)

    年龄  成绩   班级
姓名
李四  21  92  2 班
赵六  22  90  2 班

In [29]:
# （10）查询姓名是 张三或王五 的记录
data[(data.姓名 == "张三") | (data.姓名 == "王五")]

   姓名  年龄  成绩   班级
0  张三  20  85  1 班
2  王五  19  78  1 班

In [30]:
# （11）查询 成绩在 80～90 之间 的学生
data[(data.成绩 >= 80) & (data.成绩 <= 90)]
# 注意：无法使用python的语法糖(80<= data.成绩 <= 90),Pandas 的比较运算返回的是布尔 Series，而不是单个布尔值

   姓名  年龄  成绩   班级
0  张三  20  85  1 班
3  赵六  22  90  2 班
4  钱七  20  88  1 班

In [31]:
# （12）将 赵六的年龄修改为 23
data.loc['赵六', '年龄'] = 23
data

     姓名    年龄    成绩   班级
0    张三  20.0  85.0  1 班
1    李四  21.0  92.0  2 班
2    王五  19.0  78.0  1 班
3    赵六  22.0  90.0  2 班
4    钱七  20.0  88.0  1 班
赵六  NaN  23.0   NaN  NaN

In [32]:
# （13）删除 班级 这一列
data.drop('班级', axis=1)

     姓名    年龄    成绩
0    张三  20.0  85.0
1    李四  21.0  92.0
2    王五  19.0  78.0
3    赵六  22.0  90.0
4    钱七  20.0  88.0
赵六  NaN  23.0   NaN

In [33]:
# （14）删除 成绩低于 80 的行
data[data.成绩 >= 80]

   姓名    年龄    成绩   班级
0  张三  20.0  85.0  1 班
1  李四  21.0  92.0  2 班
3  赵六  22.0  90.0  2 班
4  钱七  20.0  88.0  1 班