In [1]:
# 导入 pandas 库，并简写为 pd（这是惯例用法）
import pandas as pd

In [ ]:
# 导入pandas库并创建一个DataFrame对象
# 使用pd.DataFrame()创建一个二维表格数据结构
# 参数1: [[80, 75, 90],[68,98,85]] 是数据部分，包含两行三列的数值
# 参数2: index=["小明","小红"] 指定行索引，即两个学生的姓名
# 参数3: columns=["语文","数学","英语"] 指定列名，即三门学科
df = pd.DataFrame([[80, 75, 90],[68,98,85]], index=["小明","小红"], columns=["语文","数学","英语"])
df  # 显示创建的DataFrame对象

    语文  数学  英语
小明  80  75  90
小红  68  98  85

In [5]:
# 获取DataFrame的索引
df.index

Index(['小明', '小红'], dtype='object')

In [ ]:
# 获取DataFrame中的所有数据值，以NumPy数组的形式返回
df.values

array([[80, 75, 90],
       [68, 98, 85]])

In [ ]:
# 获取DataFrame的列名
df.columns

Index(['语文', '数学', '英语'], dtype='object')

In [ ]:
# 从DataFrame中选择名为"数学"的列
df.数学

小明    75
小红    98
Name: 数学, dtype: int64

In [ ]:
# 查看df数据框中"数学"列的数据类型
type(df.数学)

pandas.core.series.Series

In [ ]:
# 获取名为"数学"的列数据
# 这是pandas DataFrame中的一种列选择方式
# 使用方括号和列名来访问特定的列
df["数学"]

小明    75
小红    98
Name: 数学, dtype: int64

In [19]:
df["历史"] = [98,97]
df

    语文  数学  英语  历史
小明  80  75  90  98
小红  68  98  85  97

In [ ]:
# 删除DataFrame中的"历史"列
del df["历史"]
# 显示DataFrame
df

    语文  数学  英语
小明  80  75  90
小红  68  98  85

In [ ]:
# 导入pandas库并创建一个DataFrame对象
df1 = pd.DataFrame({
    "month": [12, 3, 6, 9],      # 定义月份列，包含12月、3月、6月和9月
    "year": [4, 5, 6, 7],        # 定义年份列，包含4年、5年、6年和7年
    "sale": [66, 46, 73, 89]     # 定义销售额列，包含66、46、73和89四个数值
}, index=["一", "二", "三", "四"])  # 设置索引为"一"、"二"、"三"、"四"
df1  # 显示创建的DataFrame对象

   month  year  sale
一     12     4    66
二      3     5    46
三      6     6    73
四      9     7    89

In [24]:
df.index[1] = "小明"

TypeError: Index does not support mutable operations

In [26]:
df.index = ["小聪", "小明"]
df

    语文  数学  英语
小聪  80  75  90
小明  68  98  85

In [31]:
pd.DataFrame([[80, 75, 90],[68,98,85]]).index

RangeIndex(start=0, stop=2, step=1)

In [39]:
df1 = pd.DataFrame({
    "month": [12, 2, 3, 9],      # 定义月份列，包含12月、3月、6月和9月
    "year": [2013, 2014, 2015, 2016],        # 定义年份列，包含4年、5年、6年和7年
    "sale": [55, 46, 73, 89]     # 定义销售额列，包含66、46、73和89四个数值
})

In [ ]:
# 使用指定的列作为索引
# 使用多列（year和month）创建层次化索引
df1.set_index(["year", "month"])

            sale
year month
2013 12       55
2014 2        46
2015 3        73
2016 9        89

# 重置索引

In [53]:
# 导入pandas库并创建一个Series对象
data1 = pd.Series([1, 2, 3, 4, 5], index=["b", "c", "a", "e", "d"])  # 使用自定义索引创建Series，值为[1,2,3,4,5]，索引为["b","c","a","e","d"]
data1  # 输出Series对象data1

b    1
c    2
a    3
e    4
d    5
dtype: int64

In [54]:
# 使用reindex方法对数据进行重新索引
# reindex()方法用于根据新的索引标签重新排列数据
# 如果新索引标签在原数据中不存在，则填充NaN值
# 此处没有传入参数，表示使用默认行为，通常保持原有索引不变
data1.reindex()

b    1
c    2
a    3
e    4
d    5
dtype: int64

In [55]:
# 使用reindex方法对data1进行索引重排
data1.reindex(["a", "b", "c", "d", "e", "f"])  # 将data1的索引重新排列为指定的列表顺序

a    3.0
b    1.0
c    2.0
d    5.0
e    4.0
f    NaN
dtype: float64

In [56]:
# 使用reindex方法对data1进行重新索引，并指定填充值为10
data1.reindex(["a", "b", "c", "d", "e", "f"], fill_value=10)

a     3
b     1
c     2
d     5
e     4
f    10
dtype: int64

In [ ]:
# 创建一个pandas Series对象
# 使用列表[1,3,5,7]作为数据
# 指定自定义索引[0,2,4,6]
pd.Series([1,3,5,7], index=[0,2,4,6])

0    1
2    3
4    5
6    7
dtype: int64

In [ ]:
# 导入pandas库后创建的Series示例
# 使用pd.Series函数创建一个Series对象
data2 = pd.Series([1,3,5,7], index=[0,2,4,6])  # 创建一个包含值为[1,3,5,7]的Series，并指定索引为[0,2,4,6]
data2  # 输出Series对象，显示其值和索引

0    1
2    3
4    5
6    7
dtype: int64

In [67]:
# 使用reindex方法对data2进行重新索引，范围是0到5的整数
data2.reindex(range(6))

0    1.0
1    NaN
2    3.0
3    NaN
4    5.0
5    NaN
dtype: float64

In [68]:
# 使用reindex方法对data2进行重新索引
# range(6)生成索引范围0到5
# method="ffill"表示使用前向填充方法，即用前面的值填充缺失值
data2.reindex(range(6), method="ffill")

0    1
1    1
2    3
3    3
4    5
5    5
dtype: int64

In [70]:
# 使用reindex方法对data2进行重新索引，并使用method参数指定填充方法
# range(6)生成一个从0到5的整数序列作为新的索引
# method="bfill"表示使用后向填充（backward fill）方法，即用后面有效值填充缺失值
data2.reindex(range(6), method="bfill")

0    1
1    3
2    3
3    5
4    5
5    7
dtype: int64