In [1]:
import pandas as pd

In [2]:
data = pd.Series([2,3,4,5])
data

0    2
1    3
2    4
3    5
dtype: int64

In [3]:
data1 = pd.Series([2,3,4,5],index=['a','b','c','d'])
data1

a    2
b    3
c    4
d    5
dtype: int64

In [4]:
dic = {'name':'zhangsan','title':'teacher'}
data2 = pd.Series(dic)

In [5]:
data2

name     zhangsan
title     teacher
dtype: object

In [6]:
type(data)

pandas.core.series.Series

In [7]:
data2.index

Index(['name', 'title'], dtype='object')

In [8]:
data2.values

array(['zhangsan', 'teacher'], dtype=object)

In [9]:
data2[1]

C:\Users\Administrator\AppData\Local\Temp\ipykernel_1904\3753409921.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  data2[1]

'teacher'

In [10]:
data2.iloc[1]

'teacher'

In [11]:
data*2

0     4
1     6
2     8
3    10
dtype: int64

In [12]:
data2 + 'ha'

name     zhangsanha
title     teacherha
dtype: object

In [14]:
df = pd.DataFrame([[80,75,90],[68,96,85]],index=['小明','小红'],columns=['语文','数学','英语'])#创建
df

    语文  数学  英语
小明  80  75  90
小红  68  96  85

In [15]:
df.index

Index(['小明', '小红'], dtype='object')

In [16]:
df.values

array([[80, 75, 90],
       [68, 96, 85]], dtype=int64)

In [17]:
df.columns

Index(['语文', '数学', '英语'], dtype='object')

In [18]:
df.数学

小明    75
小红    96
Name: 数学, dtype: int64

In [19]:
type(df.数学)

pandas.core.series.Series

In [20]:
df['数学']

小明    75
小红    96
Name: 数学, dtype: int64

In [21]:
df['历史'] = [98,97]
df

    语文  数学  英语  历史
小明  80  75  90  98
小红  68  96  85  97

In [22]:
del df['历史']

In [23]:
df

    语文  数学  英语
小明  80  75  90
小红  68  96  85

In [24]:
df1 = pd.DataFrame({'month':[12,3,6,9],
                   'year':[2013,2014,2014,2014],
                   'sale':[55,46,73,89]
})
df1

   month  year  sale
0     12  2013    55
1      3  2014    46
2      6  2014    73
3      9  2014    89

In [25]:
df.index[1] = '小聪'

TypeError: Index does not support mutable operations

In [26]:
df.index=['小聪','小明']

In [27]:
df

    语文  数学  英语
小聪  80  75  90
小明  68  96  85

# 层次化索引

In [33]:
pd.DataFrame([80,75,90],[68,96,85]).index

Index([68, 96, 85], dtype='int64')

In [39]:
df1 = pd.DataFrame({'month':[12,3,3,9],
                   'year':[2013,2014,2014,2014],
                   'sale':[55,46,73,89]
})
df1

   month  year  sale
0     12  2013    55
1      3  2014    46
2      3  2014    73
3      9  2014    89

In [40]:
df1.set_index(['year','month'])

            sale
year month
2013 12       55
2014 3        46
     3        73
     9        89

# 重置索引

In [42]:
data1 = pd.Series([1,2,3,4,5],index=['b','c','a','e','d'])
data1

b    1
c    2
a    3
e    4
d    5
dtype: int64

In [43]:
data1.reindex(['a','b','c','d','e'])

a    3
b    1
c    2
d    5
e    4
dtype: int64

In [44]:
data1.reindex(['a','b','c','d','e','f'])

a    3.0
b    1.0
c    2.0
d    5.0
e    4.0
f    NaN
dtype: float64

In [46]:
data1.reindex(['a','b','c','d','e','f','g'],fill_value=10)

a     3
b     1
c     2
d     5
e     4
f    10
g    10
dtype: int64

In [47]:
data2 = pd.Series([1,3,5,7],index=[0,2,4,6])
data2

0    1
2    3
4    5
6    7
dtype: int64

In [48]:
data2.reindex(range(6))

0    1.0
1    NaN
2    3.0
3    NaN
4    5.0
5    NaN
dtype: float64

In [49]:
data2.reindex(range(6),method='ffill')

0    1
1    1
2    3
3    3
4    5
5    5
dtype: int64

In [52]:
data2.reindex(range(6),method='bfill')

0    1
1    3
2    3
3    5
4    5
5    7
dtype: int64

# 索引操作

In [53]:
data1 = pd.Series([1,2,3,4,5],index=['b','c','a','e','d'])
data1

b    1
c    2
a    3
e    4
d    5
dtype: int64

In [54]:
data1[1]

C:\Users\Administrator\AppData\Local\Temp\ipykernel_1904\1487329869.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  data1[1]

2

In [55]:
data1.iloc[1]

2

In [56]:
data1['c']

2

In [57]:
data1[2:4]

a    3
e    4
dtype: int64

In [58]:
data1['a':'e']

a    3
e    4
dtype: int64

In [59]:
#不连续
data1.iloc[[1,2,4]]

c    2
a    3
d    5
dtype: int64

In [62]:
data1.loc[['a','c','e']]

a    3
c    2
e    4
dtype: int64

In [63]:
#布尔索引
data1>3

b    False
c    False
a    False
e     True
d     True
dtype: bool

In [64]:
data1[data1>3]

e    4
d    5
dtype: int64

In [66]:
#dataframe索引方式
import numpy as np
df = pd.DataFrame(np.arange(12).reshape(3,4),columns=['a','b','c','d'])
df

   a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [67]:
df['b']

0    1
1    5
2    9
Name: b, dtype: int32

In [68]:
df[['b','d']]

   b   d
0  1   3
1  5   7
2  9  11

In [69]:
df[:2]

   a  b  c  d
0  0  1  2  3
1  4  5  6  7

In [70]:
df[:2][['b','d']]

   b  d
0  1  3
1  5  7

In [72]:
df.iloc[:,:2]

   a  b
0  0  1
1  4  5
2  8  9

# 算术运算

In [77]:
data1 = pd.Series(range(10,13),index=range(3))
data2 = pd.Series(range(20,25),index=range(5))

In [78]:
data1

0    10
1    11
2    12
dtype: int64

In [79]:
data2

0    20
1    21
2    22
3    23
4    24
dtype: int64

In [80]:
data1+data2

0    30.0
1    32.0
2    34.0
3     NaN
4     NaN
dtype: float64

In [83]:
data1.add(data2,fill_value=0)

0    30.0
1    32.0
2    34.0
3    23.0
4    24.0
dtype: float64

# 排序

In [84]:
data1 = pd.Series(range(10,15),index=[5,3,1,3,2])
data1

5    10
3    11
1    12
3    13
2    14
dtype: int64

In [86]:
data1.sort_index(ascending=False)

5    10
3    11
3    13
2    14
1    12
dtype: int64

In [87]:
df1 = pd.DataFrame(np.arange(9).reshape(3,3),index=[4,3,5])
df1

   0  1  2
4  0  1  2
3  3  4  5
5  6  7  8

In [88]:
df1.sort_index()

   0  1  2
3  3  4  5
4  0  1  2
5  6  7  8

In [89]:
#按值排序
data2 = pd.Series([4,np.nan,6,np.nan,-3,2])
data2

0    4.0
1    NaN
2    6.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [90]:
data2.sort_values()

4   -3.0
5    2.0
0    4.0
2    6.0
1    NaN
3    NaN
dtype: float64

In [91]:
data3=pd.DataFrame([
    [0.4,-0.1,-0.3,0.0],
    [0.2,0.6,-0.1,-0.7],
    [0.8,0.6,-0.5,0.1]
])
data3

     0    1    2    3
0  0.4 -0.1 -0.3  0.0
1  0.2  0.6 -0.1 -0.7
2  0.8  0.6 -0.5  0.1

In [92]:
data3.sort_values(by=2)

     0    1    2    3
2  0.8  0.6 -0.5  0.1
0  0.4 -0.1 -0.3  0.0
1  0.2  0.6 -0.1 -0.7

In [93]:
data3.sort_values(by=[2,3])

     0    1    2    3
2  0.8  0.6 -0.5  0.1
0  0.4 -0.1 -0.3  0.0
1  0.2  0.6 -0.1 -0.7

In [94]:
data3

     0    1    2    3
0  0.4 -0.1 -0.3  0.0
1  0.2  0.6 -0.1 -0.7
2  0.8  0.6 -0.5  0.1

In [95]:
data3.iloc[1,2] = -0.3

In [96]:
data3

     0    1    2    3
0  0.4 -0.1 -0.3  0.0
1  0.2  0.6 -0.3 -0.7
2  0.8  0.6 -0.5  0.1

In [97]:
data3.sort_values(by=[2,3])

     0    1    2    3
2  0.8  0.6 -0.5  0.1
1  0.2  0.6 -0.3 -0.7
0  0.4 -0.1 -0.3  0.0