对“某超市公司五店销售数据.xlsx”文件进行以下操作，将源代码与运行结果以截图形式上传

一、数据分组
1. 读取文件，并显示头部的数据，默认为5，也可以自由设置参数
2. 按“门店名称”列进行分组，统计总销售额
3. 按“产品类别”列进行分组，统计总利润额

二、数据聚合运算
4. 按“门店名称”列进行分组，分别统计利润额的总和和中位数，以及销售额的最大值和最小值
5. 按“产品类别”列进行分组，分别统计销售额的最大值、最小值、平均值、中位数

三、透视表和交叉表
6. 利用pivot_table创建透视表，分组后行索引为“产品类别”，列标签为“门店名称”，计算列为销售额
7. 利用cross_tab创建交叉表，分组后行索引为“产品类别”，列标签为“门店名称”，计算销售额的均值

In [1]:
import pandas as pd
import numpy as np

In [3]:
# 一、数据分组
# 1. 读取文件，并显示头部的数据，默认为5，也可以自由设置参数

# 读取文件
sales_data = pd.read_excel('某超市公司五店销售数据.xlsx')
# 显示头部的数据
sales_data.head()

,顾客姓名,门店名称,产品类别,订单日期,订单等级,产品类别编号,促销折扣,订单号,订单量,利润额,销售额,单位价格,X,Y
0,Adam Bellavance,四店,办公用品,2012-01-20,低,18,0.99,18596,288,2007,3753,12.53,0.8,6.1
1,Ashley Jarboe,一店,办公用品,2011-11-30,低,18,0.98,39490,342,-558,4104,11.97,0.8,6.1
2,Barry Gonzalez,三店,办公用品,2010-01-06,低,18,0.98,21249,198,2691,9747,48.58,0.8,6.1
3,Bill Eplett,四店,办公用品,2008-06-04,低,18,0.93,32741,117,-738,1224,9.71,0.8,6.1
4,Brian Stugart,一店,办公用品,2010-07-20,低,18,0.96,58372,432,387,1656,3.98,0.8,6.1

In [7]:

# 2. 按“门店名称”列进行分组，统计总销售额
sum_ales = sales_data.groupby('门店名称')['销售额'].sum()
sum_ales

门店名称
一店    24428268
三店    30658716
二店    26876817
五店    24808761
四店    27390879
Name: 销售额, dtype: int64

In [8]:
# 3. 按“产品类别”列进行分组，统计总利润额
sum_revenue = sales_data.groupby('产品类别')['利润额'].sum()
sum_revenue

产品类别
个人护理     291789
书本       451080
儿童家具     411174
儿童玩具     627912
儿童衣物     240624
儿童读物      73926
办公用品     765351
卫浴用品     344772
厨房用品     178371
女士运动服    433989
婴儿衣物     516213
孕妇衣物     559665
存储容器     326484
宠物用品     309609
家具产品     345492
家用工具     257085
床上用品     313542
易变质食品    540351
汽车用品     314397
清洁用品     351405
游戏产品     341883
珠宝首饰     372690
电子音像     324954
男士运动服    148491
男装       638658
窗帘布衣     320373
美容护肤     233199
耐用杂货     295191
茶、咖啡     394965
药品       395469
行李箱      310509
袜子小件     198567
装饰用品     487602
调味品      289926
零食小吃     343260
青年女装     332991
青年男装     439983
鞋类       190332
Name: 利润额, dtype: int64

In [9]:
# 二、数据聚合运算
# 4. 按“门店名称”列进行分组，分别统计利润额的总和和中位数，以及销售额的最大值和最小值
grouped_data = sales_data.groupby('门店名称')
aggregated_data = grouped_data.agg({'利润额': ['sum', 'median'], '销售额': ['max', 'min']})
aggregated_data

          利润额            销售额
          sum median     max min
门店名称
一店    2770290  -36.0  257985  18
三店    2859957    9.0  801549  27
二店    2577402  -18.0  268965  36
五店    2169072  -18.0  262674  81
四店    3335553    9.0  413316  27

In [10]:
# 5. 按“产品类别”列进行分组，分别统计销售额的最大值、最小值、平均值、中位数
grouped_data = sales_data.groupby('产品类别')
aggregated_data = grouped_data.agg({'销售额': ['max', 'min', 'mean', 'median']})
aggregated_data

          销售额
          max  min          mean  median
产品类别
个人护理   198711   54  15239.797297  4333.5
书本     801549  126  17443.381395  3033.0
儿童家具   264105   90  18767.377358  3982.5
儿童玩具   268965   36  18478.452915  5526.0
儿童衣物   183006   81  14176.018868  4212.0
儿童读物   300312   45  21688.513393  5494.5
办公用品   257985   45  17124.308036  3447.0
卫浴用品   160866   99  12642.760000  3600.0
厨房用品   235143   99  14483.239631  3915.0
女士运动服  228690   54  13770.081081  3091.5
婴儿衣物   253620  108  21375.679245  5670.0
孕妇衣物   249489   72  19010.097087  4090.5
存储容器   125298   81  12915.788018  3942.0
宠物用品   250884   90  16599.950226  4689.0
家具产品   189423   63  16001.440000  4851.0
家用工具   248976   63  15166.285714  2808.0
床上用品   173421   45  15940.755187  3150.0
易变质食品  216459   99  18783.084112  5449.5
汽车用品   209160   36  12843.739726  3150.0
清洁用品   413316   54  16677.171429  4113.0
游戏产品   235197   99  17532.242152  5868.0
珠宝首饰   190854   27  16606.566964  4216.5
电子音像   216954   18  16759.585714  3847.5
男士运动服  372087   27  16219.976636  3906.0
男装     221760   27  17422.708696  4477.5
窗帘布衣   234855   45  13820.072727  3024.0
美容护肤   186318   36  15594.925926  3078.0
耐用杂货   213984   90  13592.870079  2758.5
茶、咖啡   200880   36  17153.650862  5436.0
药品     255231   72  16986.109948  3555.0
行李箱    191889   99  14968.848214  4333.5
袜子小件   143073   45  12180.336585  3915.0
装饰用品   192834  108  13648.258929  4459.5
调味品    177363   63  17508.511211  5535.0
零食小吃   171126   72  14663.204082  3249.0
青年女装   219519   90  15705.736364  3892.5
青年男装   262674   54  15175.157676  4626.0
鞋类     140895   27  13027.202830  3415.5

In [11]:
# 三、透视表和交叉表
# 6. 利用pivot_table创建透视表，分组后行索引为“产品类别”，列标签为“门店名称”，计算列为销售额
pivot_table = sales_data.pivot_table(index='产品类别', columns='门店名称', values='销售额')
pivot_table

门店名称             一店            三店            二店            五店            四店
产品类别
个人护理   12037.153846  17603.590909  17265.638298  11172.807692  18668.925000
书本     13437.658537  29591.181818  20402.700000  13168.465116   8555.282609
儿童家具   11115.972973  19177.568182  12688.826087  28798.714286  21636.000000
儿童玩具   16981.325581  18013.500000  19172.437500  21846.461538  16383.600000
儿童衣物   19957.950000   7460.425532  14872.973684  15610.275000  14186.680851
儿童读物   17272.764706  26878.500000  12640.320000  17162.769231  36382.090909
办公用品   22513.263158  20358.878049  17278.276596  14677.434783  12661.269231
卫浴用品    6478.250000  17787.245902  10371.558140  14535.000000  10227.500000
厨房用品   13249.800000  13906.173913  19536.187500  11365.687500  13997.057143
女士运动服  16243.297297  14430.673469  15450.979592   7702.463415  14694.652174
婴儿衣物   18860.516129  29859.800000  25841.062500   9671.441860  21045.200000
孕妇衣物   19351.071429   7690.875000  20037.342857  23201.400000  27466.750000
存储容器   10262.250000  14343.750000  12854.250000  16634.655738   6087.214286
宠物用品   14556.240000  22824.000000  14155.500000  21267.439024  11550.115385
家具产品   14695.530612  15027.400000  16205.500000  14388.840000  20026.000000
家用工具   13479.480000  14972.500000  14875.024390  14983.411765  16574.580000
床上用品   14791.075472  15713.625000  19702.883721  16095.857143  14187.109091
易变质食品  17522.217391  17411.510204  14612.357143  16607.076923  28921.026316
汽车用品   13091.553191   8998.897959  19666.840909  11120.553191  11516.343750
清洁用品   11995.116279  16321.125000   6743.675676  18167.200000  30701.675676
游戏产品   17364.800000  26045.021739  17906.553191  10955.382353  14041.411765
珠宝首饰   17823.692308  19977.893617  14401.714286  21470.931818  10311.403846
电子音像   16889.727273  14812.913793  20172.731707  18368.470588  14109.272727
男士运动服  18333.391304  16882.297297  13940.250000  12150.750000  19075.212766
男装     13932.327273  19011.767442  18731.872340  15363.900000  22138.457143
窗帘布衣    8329.320000  11674.465116  10385.826923  13641.652174  21529.666667
美容护肤   16746.882353  19096.166667  11122.659574  19946.618182   7901.500000
耐用杂货   11691.000000  14372.590909  14846.203125  10053.803571  18769.750000
茶、咖啡   18033.187500  14473.032787  23671.928571  12386.634146  18228.150000
药品     10536.230769  17680.263158  20598.171429  10140.585366  26970.631579
行李箱    20705.318182  18023.553191  15946.764706   6872.580000  13686.468750
袜子小件    9065.769231  15690.150000  12306.780000  10231.024390  13742.485714
装饰用品   12384.000000  16323.171429  14898.176471  12639.326087  12493.285714
调味品    17795.250000  16323.136364  15217.826087  16490.045455  21724.600000
零食小吃   16429.384615  19482.107143  13921.772727  10524.255319  12771.915254
青年女装   16397.333333  15996.326087  14151.255319  10912.263158  21548.571429
青年男装   23584.829268  13392.705882  12147.000000  15631.258065  11757.000000
鞋类      7397.700000  17517.882353  14822.480769   5695.600000  18216.264706

In [ ]:
# 7. 利用cross_tab创建交叉表，分组后行索引为“产品类别”，列标签为“门店名称”，计算销售额的均值
# 这里我得要注意crosstab是pd才有的，目前的sales_data数据格式DataFarme其实是没有crosstab方法的，如果硬来需要整体进行数据转换
cross_table = pd.crosstab(
    index=sales_data['产品类别'],
    columns=sales_data['门店名称'],
    values=sales_data['销售额'],
    aggfunc=np.mean
)
cross_table

C:\Users\yandifei\AppData\Local\Temp\ipykernel_40920\910836051.py:3: FutureWarning: The provided callable <function mean at 0x000002120F40B600> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  cross_table = pd.crosstab(

门店名称             一店            三店            二店            五店            四店
产品类别
个人护理   12037.153846  17603.590909  17265.638298  11172.807692  18668.925000
书本     13437.658537  29591.181818  20402.700000  13168.465116   8555.282609
儿童家具   11115.972973  19177.568182  12688.826087  28798.714286  21636.000000
儿童玩具   16981.325581  18013.500000  19172.437500  21846.461538  16383.600000
儿童衣物   19957.950000   7460.425532  14872.973684  15610.275000  14186.680851
儿童读物   17272.764706  26878.500000  12640.320000  17162.769231  36382.090909
办公用品   22513.263158  20358.878049  17278.276596  14677.434783  12661.269231
卫浴用品    6478.250000  17787.245902  10371.558140  14535.000000  10227.500000
厨房用品   13249.800000  13906.173913  19536.187500  11365.687500  13997.057143
女士运动服  16243.297297  14430.673469  15450.979592   7702.463415  14694.652174
婴儿衣物   18860.516129  29859.800000  25841.062500   9671.441860  21045.200000
孕妇衣物   19351.071429   7690.875000  20037.342857  23201.400000  27466.750000
存储容器   10262.250000  14343.750000  12854.250000  16634.655738   6087.214286
宠物用品   14556.240000  22824.000000  14155.500000  21267.439024  11550.115385
家具产品   14695.530612  15027.400000  16205.500000  14388.840000  20026.000000
家用工具   13479.480000  14972.500000  14875.024390  14983.411765  16574.580000
床上用品   14791.075472  15713.625000  19702.883721  16095.857143  14187.109091
易变质食品  17522.217391  17411.510204  14612.357143  16607.076923  28921.026316
汽车用品   13091.553191   8998.897959  19666.840909  11120.553191  11516.343750
清洁用品   11995.116279  16321.125000   6743.675676  18167.200000  30701.675676
游戏产品   17364.800000  26045.021739  17906.553191  10955.382353  14041.411765
珠宝首饰   17823.692308  19977.893617  14401.714286  21470.931818  10311.403846
电子音像   16889.727273  14812.913793  20172.731707  18368.470588  14109.272727
男士运动服  18333.391304  16882.297297  13940.250000  12150.750000  19075.212766
男装     13932.327273  19011.767442  18731.872340  15363.900000  22138.457143
窗帘布衣    8329.320000  11674.465116  10385.826923  13641.652174  21529.666667
美容护肤   16746.882353  19096.166667  11122.659574  19946.618182   7901.500000
耐用杂货   11691.000000  14372.590909  14846.203125  10053.803571  18769.750000
茶、咖啡   18033.187500  14473.032787  23671.928571  12386.634146  18228.150000
药品     10536.230769  17680.263158  20598.171429  10140.585366  26970.631579
行李箱    20705.318182  18023.553191  15946.764706   6872.580000  13686.468750
袜子小件    9065.769231  15690.150000  12306.780000  10231.024390  13742.485714
装饰用品   12384.000000  16323.171429  14898.176471  12639.326087  12493.285714
调味品    17795.250000  16323.136364  15217.826087  16490.045455  21724.600000
零食小吃   16429.384615  19482.107143  13921.772727  10524.255319  12771.915254
青年女装   16397.333333  15996.326087  14151.255319  10912.263158  21548.571429
青年男装   23584.829268  13392.705882  12147.000000  15631.258065  11757.000000
鞋类      7397.700000  17517.882353  14822.480769   5695.600000  18216.264706